export const typeToColorMap = {
    normal: "#a8a979",
    fire: "#EE942A", // Rouge orangé
    fighting: "#c13029",
    water: "#A5E0E0", // Bleu
    flying: "#a891f1",
    grass: "#19CC20", // Vert
    poison: "#a041a1",
    electric: "#F9D031",
    ground: "#e0c068",
    psychic: "#f95889",
    rock: "#b9a138",
    ice: "#99d9d8",
    bug: "#a8b820", // Vert olive
    dragon: "#7138f9",
    ghost: "#705999",
    dark: "#705848",
    steel: "#b9b9d0",
    fairy: "#ef99ad",
    stellar: "#7cc6b3",
    unknown: "#5B5A5B",
};

export const typeFrenchTranslation = {
    normal: "Normal",
    fire: "Feu",
    water: "Eau",
    electric: "Électrik",
    grass: "Plante",
    ice: "Glace",
    fighting: "Combat",
    poison: "Poison",
    ground: "Sol",
    flying: "Vol",
    psychic: "Psy",
    bug: "Insecte",
    rock: "Roche",
    ghost: "Spectre",
    dragon: "Dragon",
    dark: "Ténèbres",
    steel: "Acier",
    fairy: "Fée"
};

export const abilitiesFrenchTranslation = {
    "adaptability": "Adaptabilité",
    "aerilate": "Peau Céleste",
    "aftermath": "Boom Final",
    "air-lock": "Air Lock",
    "analytic": "Analyste",
    "anger-point": "Colérique",
    "anticipation": "Anticipation",
    "arena-trap": "Piège",
    "aroma-veil": "Aroma-Voile",
    "aura-break": "Aura Inversée",
    "bad-dreams": "Mauvais Rêve",
    "battery": "Batterie",
    "battle-armor": "Armur'Baston",
    "battle-bond": "Synergie",
    "beast-boost": "Boost Chimère",
    "berserk": "Dracolère",
    "big-pecks": "Cœur de Coq",
    "blaze": "Brasier",
    "bulletproof": "Pare-Balles",
    "cheek-pouch": "Bajoues",
    "chlorophyll": "Chlorophylle",
    "clear-body": "Corps Sain",
    "cloud-nine": "Ciel Gris",
    "color-change": "Déguisement",
    "comatose": "Hypersommeil",
    "competitive": "Battant",
    "compound-eyes": "Œil Composé",
    "contrary": "Contestation",
    "corrosion": "Corrosion",
    "cursed-body": "Corps Maudit",
    "cute-charm": "Joli Sourire",
    "damp": "Moiteur",
    "dancer": "Danseuse",
    "dark-aura": "Aura Ténébreuse",
    "dauntless-shield": "Égide Inflexible",
    "dazzling": "Corps Coloré",
    "defeatist": "Défaitiste",
    "defiant": "Acharné",
    "delta-stream": "Souffle Delta",
    "desolate-land": "Terre Finale",
    "disguise": "Déguisement",
    "download": "Télécharge",
    "dragon's-maw": "Mâchoire de Dragon",
    "drizzle": "Crachin",
    "drought": "Sécheresse",
    "dry-skin": "Peau Sèche",
    "early-bird": "Matinal",
    "effect-spore": "Pose Spore",
    "electric-surge": "Créa-Élec",
    "emergency-exit": "Repli Tactique",
    "fairy-aura": "Aura Féérique",
    "filter": "Filtre",
    "flame-body": "Corps Ardent",
    "flare-boost": "Rage Brûlure",
    "flash-fire": "Torche",
    "flower-gift": "Don Floral",
    "flower-veil": "Flora-Voile",
    "fluffy": "Boule de Poils",
    "forecast": "Météo",
    "forewarn": "Prédiction",
    "friend-guard": "Garde Amie",
    "frisk": "Fouille",
    "full-metal-body": "Métallo-Garde",
    "fur-coat": "Toison Épaisse",
    "gale-wings": "Ailes Bourrasque",
    "galvanize": "Peau Électrique",
    "gluttony": "Gloutonnerie",
    "gooey": "Poisseux",
    "gorilla-tactics": "Tactique Gorille",
    "grass-pelt": "Toison Herbue",
    "grassysurge": "Créa-Herbe",
    "guts": "Cran",
    "harvest": "Récolte",
    "healer": "Cœur Soin",
    "heatproof": "Ignifu-Voile",
    "heavy-metal": "Heavy Metal",
    "honey-gather": "Cherche Miel",
    "huge-power": "Coloforce",
    "hungerswitch": "Estomac Repli",
    "hustle": "Agitation",
    "hydration": "Hydratation",
    "hypercutter": "Hyper Cutter",
    "ice-body": "Corps Gel",
    "ice-face": "Face de Glace",
    "ice-scales": "Écailles de Glace",
    "illuminate": "Lumiatirance",
    "illusion": "Illusion",
    "immunity": "Vaccin",
    "imposter": "Imposteur",
    "infiltrator": "Infiltration",
    "innards-out": "Expuls'Organes",
    "inner-focus": "Attention",
    "insomnia": "Insomnia",
    "intimidate": "Intimidation",
    "intrepidsword": "Lame Indomptable",
    "iron-barbs": "Épine de Fer",
    "iron-fist": "Poing de Fer",
    "justified": "Cœur Noble",
    "keen-eye": "Regard Vif",
    "klutz": "Maladresse",
    "leaf-guard": "Feuille Garde",
    "levitate": "Lévitation",
    "libero": "Libéro",
    "light-metal": "Light Metal",
    "lightning-rod": "Paratonnerre",
    "limber": "Échauffement",
    "liquid-ooze": "SuinToxique",
    "liquid-voice": "Hydrata-Son",
    "long-reach": "Allonge",
    "magic-bounce": "Miroir Magik",
    "magic-guard": "Garde Magik",
    "magician": "Magicien",
    "magma-armor": "Armumagma",
    "magnet-pull": "Magnépiège",
    "marvel-scale": "Écaille Spéciale",
    "megalauncher": "Méga-Blaster",
    "merciless": "Sans Pitié",
    "mimicry": "Mimétisme",
    "minus": "Minus",
    "mirror-armor": "Miroir Armure",
    "mistysurge": "Créa-Brume",
    "mold-breaker": "Brise Moule",
    "moody": "Lunatique",
    "motor-drive": "Motorisé",
    "moxie": "Impudence",
    "multiscale": "Multiécaille",
    "multitype": "Multi-Type",
    "mummy": "Momie",
    "natural-cure": "Médic Nature",
    "neuroforce": "Force Cérébrale",
    "neutralizing-gas": "Gaz Inhibiteur",
    "no-guard": "Annule Garde",
    "normalize": "Normalise",
    "oblivious": "Benêt",
    "overcoat": "Envelocape",
    "overgrow": "Engrais",
    "owntempo": "Tempo Perso",
    "parental-bond": "Amour Filial",
    "pastelveil": "Voile Pastel",
    "perish-body": "Corps Condamné",
    "pickpocket": "Pickpocket",
    "pickup": "Ramassage",
    "pixilate": "Peau Féérique",
    "plus": "Plus",
    "poison-heal": "Soin Poison",
    "poison-point": "Point Poison",
    "poison-touch": "Toxitouche",
    "power-construct": "Rassemblement",
    "power-of-alchemy": "Force Chimère",
    "prankster": "Farceur",
    "pressure": "Pression",
    "primordial-sea": "Mer Primaire",
    "prism-armor": "Prisme-Armure",
    "propellertail": "Queue-Turbo",
    "protean": "Protéen",
    "psychicsurge": "Créa-Psy",
    "punk-rock": "Punk Rock",
    "pure-power": "Force Pure",
    "queenly-majesty": "Prestance Royale",
    "quick-draw": "Dégainage Rapide",
    "quick-feet": "Pied Véloce",
    "rain-dish": "Cuvette",
    "rattled": "Phobique",
    "receiver": "Receveur",
    "reckless": "Téméraire",
    "refrigerate": "Peau Gelée",
    "regenerator": "Régé-Force",
    "rivalry": "Rivalité",
    "rkssystem": "Système Alpha",
    "rock-head": "Tête de Roc",
    "rough-skin": "Peau Dure",
    "run-away": "Fuite",
    "sand-force": "Force Sable",
    "sand-rush": "Baigne Sable",
    "sand-spit": "Expuls'Sable",
    "sand-stream": "Sable Volant",
    "sand-veil": "Voile Sable",
    "sapsipper": "Herbivore",
    "schooling": "Banc",
    "scrappy": "Querelleur",
    "screencleaner": "Anti-Écran",
    "serenegrace": "Sérénité",
    "shadow-shield": "Spectro-Bouclier",
    "shadow-tag": "Marque Ombre",
    "shed-skin": "Mue",
    "sheer-force": "Sans Limite",
    "shell-armor": "Coque Armure",
    "shield-dust": "Écran Poudre",
    "shields-down": "Bouclier-Carcan",
    "simple": "Simple",
    "skill-link": "Multi-Coups",
    "slow-start": "Début Calme",
    "slush-rush": "Chasse-Neige",
    "sniper": "Sniper",
    "snow-cloak": "Rideau Neige",
    "snow-warning": "Alerte Neige",
    "solar-power": "Force Soleil",
    "solid-rock": "Solide Roc",
    "soul-heart": "Animacœur",
    "soundproof": "Anti-Bruit",
    "speed-boost": "Turbo",
    "stakeout": "Filature",
    "stall": "Frein",
    "stalwart": "Cœur Vaillant",
    "stamina": "Endurance",
    "stance-change": "Déclic Tactique",
    "static": "Statik",
    "steadfast": "Impassible",
    "steam-engine": "Turbo-Chaud",
    "steel-spirit": "Âme d'Acier",
    "steelworker": "Expert Acier",
    "stench": "Puanteur",
    "sticky-hold": "Glue",
    "storm-drain": "Lavabo",
    "strong-jaw": "Prognathe",
    "sturdy": "Fermeté",
    "suction-cups": "Ventouse",
    "super-luck": "Chanceux",
    "surgesurfer": "Surf Caudal",
    "swarm": "Essaim",
    "sweet-veil": "Gluco-Voile",
    "swift-swim": "Glissade",
    "symbiosis": "Symbiose",
    "synchronize": "Synchro",
    "tangled-feet": "Pieds Confus",
    "tangling-hair": "Mèche Rebelle",
    "technician": "Technicien",
    "telepathy": "Télépathe",
    "teravolt": "Téra-Voltage",
    "thick-fat": "Isograisse",
    "tinted-lens": "Lentiteintée",
    "torrent": "Torrent",
    "tough-claws": "Griffe Dure",
    "toxic-boost": "Rage Poison",
    "trace": "Calque",
    "transistor": "Transistor",
    "triage": "Prioguérison",
    "truant": "Absentéisme",
    "turboblaze": "TurboBrasier",
    "unaware": "Inconscient",
    "unburden": "Délestage",
    "unnerve": "Tension",
    "victorystar": "Victorieux",
    "vitalspirit": "Esprit Vital",
    "volt-absorb": "Absorb Volt",
    "wanderingspirit": "Âme Vagabonde",
    "water-absorb": "Absorb Eau",
    "water-bubble": "Aquabulle",
    "water-compaction": "Sable Humide",
    "water-veil": "Ignifu-Voile",
    "weak-armor": "Armurouillée",
    "white-smoke": "Écran Fumée",
    "wimp-out": "Escampette",
    "wonder-guard": "Garde Mystik",
    "wonderskin": "Peau Miracle",
    "zen-mode": "Mode Transe",
    "mountaineer": "Alpiniste",
    "wave-rider": "Cavalier des Vagues",
    "skater": "Patineur",
    "thrust": "Impulsion",
    "perception": "Perception",
    "parry": "Parade",
    "instinct": "Instinct",
    "dodge": "Esquive",
    "jagged-edge": "Bord Serré",
    "frostbite": "Gelure",
    "tenacity": "Ténacité",
    "pride": "Fierté",
    "deep-sleep": "Sommeil Profond",
    "power-nap": "Sieste Énergétique",
    "spirit": "Esprit",
    "warm-blanket": "Couverture Chaude",
    "gulp": "Gorgée",
    "herbivore": "Herbivore",
    "sandpit": "Bac à Sable",
    "hot-blooded": "Sang-Chaud",
    "medic": "Médecin",
    "life-force": "Force Vitale",
    "lunchbox": "Boîte à Déjeuner",
    "nurse": "Infirmière",
    "melee": "Mêlée",
    "sponge": "Éponge",
    "bodyguard": "Garde du Corps",
    "hero": "Héros",
    "last-bastion": "Dernier Bastion",
    "stealth": "Furtivité",
    "vanguard": "Avant-Garde",
    "nomad": "Nomade",
    "sequence": "Séquence",
    "grass-cloak": "Cape d'Herbe",
    "celebrate": "Célébration",
    "lullaby": "Berceuse",
    "calming": "Apaisement",
    "daze": "Étourdissement",
    "frighten": "Effrayer",
    "interference": "Interférence",
    "mood-maker": "Créateur d'Ambiance",
    "confidence": "Confiance",
    "fortune": "Fortune",
    "bonanza": "Bonanza",
    "explode": "Explosion",
    "omnipotent": "Omnipotent",
    "share": "Partage",
    "black-hole": "Trou Noir",
    "shadow-dash": "Dash Ombre",
    "sprint": "Sprint",
    "disgust": "Dégout",
    "high-rise": "Haute Élévation",
    "climber": "Grimpeur",
    "flame-boost": "Boost de Flamme",
    "aqua-boost": "Boost Aquatique",
    "run-up": "Élan",
    "conqueror": "Conquérant",
    "shackle": "Entrave",
    "decoy": "Leurre",
    "shield": "Bouclier",
    "vital-spirit": "Esprit Vital",
    "own-tempo": "Tempo Perso",
    "hyper-cutter": "Hyper Cutter"
}